/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 donut_item.glb 
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/donut_item.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.005']}
        position={[0.19, 0.054, 0.01]}
        scale={-0.096}
      />
      <mesh
        geometry={nodes.donut005.geometry}
        material={materials['Material.002']}
        position={[-0.007, 0.455, -0.006]}
        rotation={[-0.346, 0.058, -0.87]}
        scale={1.09}
      >
        <mesh
          geometry={nodes.icing004.geometry}
          material={materials['Material.001']}
          position={[0.001, 0.001, -0.001]}
          scale={1.129}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('/donut_item.glb');
